name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Run dotnet format
      id: format
      run: dotnet format
      
    - name: Commit files
      if: steps.format.outputs.has-changes == 'true'
      uses: EndBug/add-and-commit@v4.1.0
      with:
          author_name: Github Actions
          author_email: actions@github.com
          message: Automated dotnet-format update
          ref: ${{ github.head_ref }}
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
    
    - name: Test
      run: dotnet test --no-build --verbosity normal
